apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongoexpress
  name: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: hzbook.azurecr.io/mongo-express
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        resources: {}
        env:
          - name: ME_CONFIG_BASICAUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: mongo-express-username
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: mongo-express-password
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: mongo-express-database-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: mongo-express-database-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: mongo-express-database-url
          - name: ME_CONFIG_MONGODB_PORT
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: mongo-express-database-port
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: 'true'
      imagePullSecrets:
      - name: acr-secret
