apiVersion: v1
kind: Service
metadata:
  name: hzbook
  labels:
    app: hzbook
    component: microservice
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hzbook
  sessionAffinity: None
  type: LoadBalancer
