# Default values for hx-apicore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hzbook.azurecr.io/hzbook
  pullPolicy: Always
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

podTerminationGracePeriodSeconds: 1800

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: 8000-8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

envVars:
  ENV: dev

extraEnvVars: {}