kind: Deployment
apiVersion: apps/v1
metadata:
  name: hzbook
  labels:
    app: hzbook
    component: microservice
spec:
  selector:
    matchLabels:
      app: hzbook
      component: microservice
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  progressDeadlineSeconds: 300
  template:
    metadata:
      name: hzbook
      labels:
        app: hzbook
        component: microservice
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: hzbook
        image: hzbook.azurecr.io/hzbook:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sleep", "20" ]
        resources: {}
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: hzbook-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: hzbook-secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: hzbook-secret
                key: DB_PASS
        ports:
        - name: hzbook
          containerPort: 8000
      imagePullSecrets:
      - name: acr-secret
