apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongoexpress
  name: mongoexpress
spec:
  ports:
  - name: tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mongoexpress
  type: LoadBalancer